# 2-я версия манифеста
apiVersion: apps/v1
kind: Deployment
metadata:
  name: app-deployment
  # Хоть и не было сказано, решил указать namespace для дальнейшей изоляции
  namespace: development 
  labels:
    app: web-app
spec:
  # Создаем 4 пода под пиковую нагрузку, потом будет настроено горизонтальное масштабирование
  replicas: 4 
  strategy:
    type: RollingUpdate # RollingUpdate для плавного обновления
    rollingUpdate:
      maxUnavailable: 0 # Запрещаем отключать под, пока не поднимется его замена
      maxSurge: 1 # Поднимаем по одному новому поду
  # Под считается "ready" только через 10 секунд, чтобы успел проинициализироваться
  minReadySeconds: 10 
  selector:
    matchLabels:
      app: web-app
  template:
    metadata:
      labels:
        app: web-app
    spec:
      containers:
        - name: web-app
          # Образ берем с указанием registry, если используется локальный
          image: company.registry/web-app:v1.0.1 # Явно указан тег для предсказуемости и контроля
          ports:
            - containerPort: 8080 # Настраивается в соответствии с приложением и политикой компании
          resources:
            requests: # Минимальный запрос на ресурсы поставил по данным о стандартном потреблении
              cpu: "100m"
              memory: 128Mi
            limits: # Лимиты выставлены для ограничения ресурсов контейнера \
              cpu: "700m" # \ с учетом высокого потребления на первые запросы (требует тестирования)
              memory: 256Mi